# This is a basic workflow to help you get started with Actions

name: Build bundles

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, deb_packages ]
  pull_request:
    branches: [ master, deb_packages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64

      - run: |
          ./install_compilation_dependencies.sh

      - name: Compile the code and make bundles
        run: |
          flutter config --enable-linux-desktop

          flutter build linux --debug
          make debug_bundle -j6
          
          flutter build linux --profile
          make profile_bundle -j6

          flutter build linux --release
          make release_bundle -j6

      - name: Prepare deb file hierarchy
        run: |
          mkdir -p .debpkg_debug/opt/zenith
          cp build/zenith/debug/bundle/* .debpkg_debug/opt/zenith
          chmod +x .debpkg_debug/opt/zenith/zenith
          
          mkdir -p .debpkg_profile/opt/zenith
          cp build/zenith/profile/bundle/* .debpkg_profile/opt/zenith
          chmod +x .debpkg_profile/opt/zenith/zenith
          
          mkdir -p .debpkg_release/opt/zenith
          cp build/zenith/release/bundle/* .debpkg_release/opt/zenith
          chmod +x .debpkg_release/opt/zenith/zenith

      - uses: jiro4989/build-deb-action@v2
        with:
          package: zenith
          package_root: .debpkg_debug
          maintainer: 'Alex Rosca'
          version: 'debug'
          arch: 'amd64'
          depends: 'libwlroots10 (>= 0.15.1), libegl1, libgles2, libepoxy0, libwayland-server0, libxkbcommon0, libpixman-1-0, libinput10'
          desc: 'Zenith desktop environment'

      - uses: jiro4989/build-deb-action@v2
        with:
          package: zenith
          package_root: .debpkg_profile
          maintainer: 'Alex Rosca'
          version: 'profile'
          arch: 'amd64'
          depends: 'libwlroots10 (>= 0.15.1), libegl1, libgles2, libepoxy0, libwayland-server0, libxkbcommon0, libpixman-1-0, libinput10'
          desc: 'Zenith desktop environment'

      - uses: jiro4989/build-deb-action@v2
        with:
          package: zenith
          package_root: .debpkg_release
          maintainer: 'Alex Rosca'
          version: 'release'
          arch: 'amd64'
          depends: 'libwlroots10 (>= 0.15.1), libegl1, libgles2, libepoxy0, libwayland-server0, libxkbcommon0, libpixman-1-0, libinput10'
          desc: 'Zenith desktop environment'

      - name: Archive debug bundle
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'build/zenith/debug/bundle/'
          filename: 'debug_bundle.zip'

      - name: Archive profile bundle
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'build/zenith/profile/bundle/'
          filename: 'profile_bundle.zip'

      - name: Archive release bundle
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'build/zenith/release/bundle/'
          filename: 'release_bundle.zip'

      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "release-${{ github.run_id }}"
          prerelease: false
          files: |
            *.deb
